/**
 * Upstream paths the BFF proxy is allowed to forward to. Keeping this closed
 * prevents the route handler from becoming an open proxy (SSRF).
 */
const ALLOWED: { method: string; pattern: RegExp }[] = [
  { method: "POST", pattern: /^v1\/auth\/login$/ },
  { method: "POST", pattern: /^v1\/auth\/logout$/ },
  { method: "GET", pattern: /^v1\/account\/me$/ },
  { method: "GET", pattern: /^v1\/account\/notifications$/ },
  { method: "GET", pattern: /^v1\/account\/notifications\/unread-count$/ },
  { method: "DELETE", pattern: /^v1\/account\/notifications$/ },
  { method: "PATCH", pattern: /^v1\/account\/notifications\/status$/ },
  { method: "POST", pattern: /^v1\/account\/notifications\/token$/ },
  { method: "GET", pattern: /^v1\/admin\/users$/ },
  { method: "PATCH", pattern: /^v1\/admin\/user-status$/ },
  { method: "PATCH", pattern: /^v1\/admin\/user-type$/ },
  { method: "GET", pattern: /^v1\/account\/users\/me\/dashboard$/ },
  { method: "PATCH", pattern: /^v1\/account\/users\/me\/profile$/ },
  { method: "PATCH", pattern: /^v1\/account\/users\/me\/password$/ },
  { method: "PATCH", pattern: /^v1\/account\/users\/me\/initial-password$/ },
  { method: "DELETE", pattern: /^v1\/account\/users\/me$/ },
  { method: "POST", pattern: /^v1\/customers$/ },
  { method: "POST", pattern: /^v1\/customers\/import$/ },
  { method: "POST", pattern: /^v1\/broadcasts$/ },
  { method: "GET", pattern: /^v1\/broadcasts$/ },
  { method: "GET", pattern: /^v1\/broadcasts\/recipients$/ },
  { method: "PATCH", pattern: /^v1\/broadcasts\/\d+\/cancel$/ },
  { method: "DELETE", pattern: /^v1\/broadcasts\/\d+$/ },
  { method: "GET", pattern: /^v1\/customers$/ },
  { method: "DELETE", pattern: /^v1\/customers$/ },
  { method: "PATCH", pattern: /^v1\/customers\/status$/ },
  { method: "GET", pattern: /^v1\/customers\/\d+$/ },
  { method: "PATCH", pattern: /^v1\/customers\/\d+$/ },
  { method: "GET", pattern: /^v1\/customers\/tags$/ },
  { method: "GET", pattern: /^v1\/wa\/user-phone-numbers$/ },
  { method: "GET", pattern: /^v1\/wa\/messages$/ },
  { method: "GET", pattern: /^v1\/wa\/messages\/\d+$/ },
  { method: "POST", pattern: /^v1\/wa\/messages$/ },
  { method: "POST", pattern: /^v1\/wa\/messages\/chat-token$/ },
  { method: "GET", pattern: /^v1\/wa\/media$/ },
  { method: "POST", pattern: /^v1\/wa\/media$/ },
  { method: "DELETE", pattern: /^v1\/wa\/phone-numbers$/ },
  { method: "POST", pattern: /^v1\/wa\/phone-numbers\/\d+\/disconnect$/ },
  { method: "POST", pattern: /^v1\/wa\/phone-numbers\/\d+\/reconnect$/ },
  { method: "GET", pattern: /^v1\/wa\/phone-numbers\/usage$/ },
  { method: "GET", pattern: /^v1\/wa\/templates$/ },
  { method: "GET", pattern: /^v1\/wa\/templates\/[^/]+$/ },
  { method: "GET", pattern: /^v1\/wa\/sample-templates$/ },
  { method: "POST", pattern: /^v1\/wa\/templates$/ },
  { method: "POST", pattern: /^v1\/wa\/templates\/upload-example$/ },
  { method: "POST", pattern: /^v1\/wa\/templates\/from-sample$/ },
  { method: "DELETE", pattern: /^v1\/wa\/templates$/ },
  { method: "GET", pattern: /^v1\/wa\/templates\/usage$/ },
  { method: "GET", pattern: /^v1\/wa\/business-accounts$/ },
  { method: "PATCH", pattern: /^v1\/wa\/business-accounts$/ },
  { method: "GET", pattern: /^v1\/wa\/business-accounts\/usage$/ },
  { method: "GET", pattern: /^v1\/wa\/phone-numbers\/\d+$/ },
  { method: "GET", pattern: /^v1\/wa\/catalogs$/ },
  { method: "GET", pattern: /^v1\/wa\/catalogs\/[^/]+$/ },
  { method: "GET", pattern: /^v1\/wa\/catalogs\/[^/]+\/sets$/ },
  { method: "GET", pattern: /^v1\/wa\/catalogs\/[^/]+\/products$/ },
  { method: "GET", pattern: /^v1\/wa\/product-sets\/[^/]+\/products$/ },
];

export function isAllowedUpstream(method: string, path: string) {
  return ALLOWED.some(
    (entry) => entry.method === method.toUpperCase() && entry.pattern.test(path),
  );
}
